-- MySQL Script generated by MySQL Workbench
-- Sun Nov  9 14:34:13 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bips_fallstudie
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bips_fallstudie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bips_fallstudie` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `bips_fallstudie` ;

-- -----------------------------------------------------
-- Table `bips_fallstudie`.`abschlussarbeit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bips_fallstudie`.`abschlussarbeit` ;

CREATE TABLE IF NOT EXISTS `bips_fallstudie`.`abschlussarbeit` (
  `idAbschlussarbeit` INT NOT NULL AUTO_INCREMENT,
  `deadline` DATETIME NULL DEFAULT NULL,
  `kolloquiumtermin` DATETIME NULL DEFAULT NULL,
  `kolloquiumraum` VARCHAR(45) NULL DEFAULT NULL,
  `kolloquiumanmerkung` VARCHAR(45) NULL DEFAULT NULL,
  `thema` VARCHAR(45) NOT NULL,
  `vonpabestaetigt` TINYINT NULL DEFAULT NULL,
  `vonssbbestaetigt` TINYINT NULL DEFAULT NULL,
  `fk_iderstbetreuer` INT NOT NULL,
  `vonerstbetreuerbestaetigt` TINYINT NULL DEFAULT NULL,
  `fk_idzweitbetreuer` INT NOT NULL,
  `vonzweitbetreuerbestaetigt` TINYINT NULL DEFAULT NULL,
  `fk_idstudent` INT NOT NULL,
  `angemeldetam` DATETIME NULL DEFAULT NULL,
  `betreuerbestatigtam` DATETIME NULL DEFAULT NULL,
  `zweitbetreuerbestaetigtam` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idAbschlussarbeit`),
  INDEX `idstudent_idx` (`fk_idstudent` ASC) VISIBLE,
  INDEX `iderstbetreuer_idx` (`fk_iderstbetreuer` ASC) VISIBLE,
  INDEX `idzweitbetreuer_idx` (`fk_idzweitbetreuer` ASC) VISIBLE,
  CONSTRAINT `iderstbetreuer`
    FOREIGN KEY (`fk_iderstbetreuer`)
    REFERENCES `bips_fallstudie`.`betreuer` (`idBetreuer`),
  CONSTRAINT `idstudent`
    FOREIGN KEY (`fk_idstudent`)
    REFERENCES `bips_fallstudie`.`student` (`matnr`),
  CONSTRAINT `idzweitbetreuer`
    FOREIGN KEY (`fk_idzweitbetreuer`)
    REFERENCES `bips_fallstudie`.`betreuer` (`idBetreuer`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bips_fallstudie`.`betreuer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bips_fallstudie`.`betreuer` ;

CREATE TABLE IF NOT EXISTS `bips_fallstudie`.`betreuer` (
  `idBetreuer` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idBetreuer`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bips_fallstudie`.`projektseminararbeit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bips_fallstudie`.`projektseminararbeit` ;

CREATE TABLE IF NOT EXISTS `bips_fallstudie`.`projektseminararbeit` (
  `idprojektSeminararbeit` INT NOT NULL AUTO_INCREMENT,
  `abgeschlossen` TINYINT NULL DEFAULT '0',
  `eigenstaendigkeitbestaetigt` TINYINT NULL DEFAULT NULL,
  `fk_idbetreuer` INT NULL DEFAULT NULL,
  `vonbetreuerbestaetigt` TINYINT NULL DEFAULT NULL,
  `typ` ENUM('seminar', 'projekt') NULL DEFAULT NULL,
  `unterschrift` VARCHAR(200) NULL DEFAULT NULL,
  `angemeldetam` DATETIME NULL DEFAULT NULL,
  `betreuerbestaetigtam` DATETIME NULL DEFAULT NULL,
  `abgegebenvon` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idprojektSeminararbeit`),
  INDEX `idbetreuer_idx` (`fk_idbetreuer` ASC) VISIBLE,
  INDEX `fk_unterschriebenVon_idx` (`abgegebenvon` ASC) VISIBLE,
  CONSTRAINT `fk_unterschriebenVon`
    FOREIGN KEY (`abgegebenvon`)
    REFERENCES `bips_fallstudie`.`student` (`matnr`),
  CONSTRAINT `idbetreuer`
    FOREIGN KEY (`fk_idbetreuer`)
    REFERENCES `bips_fallstudie`.`betreuer` (`idBetreuer`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bips_fallstudie`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bips_fallstudie`.`student` ;

CREATE TABLE IF NOT EXISTS `bips_fallstudie`.`student` (
  `matnr` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `fkstudiengang` INT NOT NULL,
  PRIMARY KEY (`matnr`),
  INDEX `idstudiengang_idx` (`fkstudiengang` ASC) VISIBLE,
  CONSTRAINT `idstudiengang`
    FOREIGN KEY (`fkstudiengang`)
    REFERENCES `bips_fallstudie`.`studiengang` (`idstudiengang`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bips_fallstudie`.`student_projektseminararbeit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bips_fallstudie`.`student_projektseminararbeit` ;

CREATE TABLE IF NOT EXISTS `bips_fallstudie`.`student_projektseminararbeit` (
  `fk_idstudent` INT NOT NULL,
  `fk_idprojektseminararbeit` INT NOT NULL,
  PRIMARY KEY (`fk_idstudent`, `fk_idprojektseminararbeit`),
  INDEX `idprojektseminararbeit_idx` (`fk_idprojektseminararbeit` ASC) VISIBLE,
  CONSTRAINT `fk_idprojektseminararbeit`
    FOREIGN KEY (`fk_idprojektseminararbeit`)
    REFERENCES `bips_fallstudie`.`projektseminararbeit` (`idprojektSeminararbeit`),
  CONSTRAINT `fk_idstudent`
    FOREIGN KEY (`fk_idstudent`)
    REFERENCES `bips_fallstudie`.`student` (`matnr`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `bips_fallstudie`.`studiengang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bips_fallstudie`.`studiengang` ;

CREATE TABLE IF NOT EXISTS `bips_fallstudie`.`studiengang` (
  `idstudiengang` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idstudiengang`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
